"""empty message

Revision ID: 651d8ed57831
Revises: cba5298c1442
Create Date: 2025-05-05 02:15:48.567299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651d8ed57831'
down_revision = 'cba5298c1442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_name_of_people_key', type_='unique')

    with op.batch_alter_table('user_people_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_people_favorites_person_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['character_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_people_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_people_favorites_person_id_fkey', 'people', ['person_id'], ['id'])
        batch_op.drop_column('character_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_name_of_people_key', ['name_of_people'])

    # ### end Alembic commands ###
