"""empty message

Revision ID: 9fe466a1c130
Revises: 912191d7916d
Create Date: 2025-05-03 03:21:51.615372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe466a1c130'
down_revision = '912191d7916d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_people', sa.String(length=120), nullable=False))
        batch_op.drop_column('data_of_people')
        batch_op.drop_column('people_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_planets', sa.String(length=120), nullable=False))
        batch_op.drop_column('planets_id')
        batch_op.drop_column('data_of_planets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_of_planets', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('name_of_planets')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('data_of_people', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('name_of_people')

    # ### end Alembic commands ###
